### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by jasonz-ncc42** [JokeJason/pokertk#6]
- [ ]  Fix css of Filter component
- [ ] Fix Poke logo size via css
- [ ] Add day/night toggle in header
- [ ] Add github icon in header
- [ ] Use material.ui to display pokemon cards
- [ ] Fix round corner of InfoDialog component
- [ ] Add error handling for data fetching across app
- [ ] Use GraphQL to query pokemons according region
- [ ] Fix image render issue as some pokemon does not has Dreamword -> front image
